export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//Layers
export const ADD_LAYER = 'ADD_LAYER';
export const DELETE_LAYER = 'DELETE_LAYER';
export const ACTIVATE_LAYER = 'ACTIVATE_LAYER';
export const RENAME_LAYER = 'RENAME_LAYER';
export const CHANGE_LAYER_VIEW = 'CHANGE_LAYER_VIEW';

//Search
export const SEARCH_BOND = 'SEARCH_BOND';

//Filters
export const FILTERS_CHANGE = 'FILTERS_CHANGE';
export const FILTERS_ISINS_CHANGE = 'FILTERS_ISINS_CHANGE';