export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//Layers
export const ADD_SET = 'ADD_SET';
export const ADD_SPREAD = 'ADD_SPREAD';
export const REMOVE_LAYER = 'REMOVE_LAYER';
export const ACTIVATE_LAYER = 'ACTIVATE_LAYER';
export const RENAME_LAYER = 'RENAME_LAYER';
export const CHANGE_LAYER_VIEW = 'CHANGE_LAYER_VIEW';

export const LAYER_SEARCH_QUERY_CHANGE = 'LAYER_SEARCH_QUERY_CHANGE';
export const LAYER_SEARCH_ISINS_CHANGE = 'LAYER_SEARCH_ISINS_CHANGE';
export const LAYER_SEARCH_ERROR = 'LAYER_SEARCH_ERROR';
export const LAYER_FILTERS_ISINS_CHANGE = 'LAYER_FILTERS_ISINS_CHANGE';
export const LAYER_FILTERS_STATS_CHANGE = 'LAYER_FILTERS_STATS_CHANGE';
export const LAYER_FILTERS_CHANGE = 'LAYER_FILTERS_CHANGE';
export const LAYER_FILTERS_ERROR = 'LAYER_FILTERS_ERROR';
export const LAYER_BONDS_UPDATE = 'LAYER_BONDS_UPDATE';

//HOME SEARCH
export const HOME_SEARCH_QUERY_CHANGE = 'HOME_SEARCH_QUERY_CHANGE';
export const HOME_SEARCH_RESPONSE = 'HOME_SEARCH_RESPONSE';
export const HOME_SEARCH_DAILY = 'HOME_SEARCH_DAILY';
export const HOME_SEARCH_ERROR = 'HOME_SEARCH_ERROR';

//Movers
export const LOAD_MOVERS = 'LOAD_MOVERS';
export const LOAD_MOVERS_SUCCESS = 'LOAD_MOVERS_SUCCESS';
export const LOAD_MOVERS_FAILURE = 'LOAD_MOVERS_FAILURE';

//BOND PAGE
export const ADD_PEER_TO_CHART = 'ADD_PEER_TO_CHART'
export const REMOVE_PEER_FROM_CHART = 'REMOVE_PEER_FROM_CHART'
export const TOGGLE_BENCHMARK = 'TOGGLE_BENCHMARK'

//Bond Info
export const OPEN_BOND_INFO = 'OPEN_BOND_INFO';
export const CLOSE_BOND_INFO = 'CLOSE_BOND_INFO';
